# Generated by Django 2.0.8 on 2019-01-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0004_auto_20190127_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('school_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='school.School')),
            ],
        ),
    ]
