# Generated by Django 2.1.1 on 2018-09-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180907_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_departments', to='accounts.School')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='is_accepting_applications',
            field=models.BooleanField(default=False),
        ),
    ]
