# Generated by Django 2.1.1 on 2018-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180907_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='max_batch_size',
        ),
        migrations.AddField(
            model_name='batch',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='max_batch_size',
            field=models.IntegerField(blank=True, help_text='Maximum students to enroll each year in a batch', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2018, unique=True),
        ),
    ]
