# Generated by Django 2.1.1 on 2018-09-08 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180907_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='is_accepting_applications',
        ),
        migrations.AddField(
            model_name='batch',
            name='application_acceptance_end_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='application_acceptance_start_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
