# Generated by Django 2.1.1 on 2018-09-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180908_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='date_of_birth',
        ),
    ]
