# Generated by Django 2.1.1 on 2018-09-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180908_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='application_reviews_required',
            field=models.IntegerField(default=1, help_text='Reviews required for each application received'),
        ),
    ]
