# Generated by Django 2.1.1 on 2018-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_school_application_reviews_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2018),
        ),
    ]
