# Generated by Django 2.0.8 on 2019-01-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('school', '0004_auto_20190127_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('application_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='score_application', to='application.Application')),
                ('school_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='score_school', to='school.School')),
            ],
        ),
    ]
