# Generated by Django 2.1.1 on 2018-09-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180907_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_text', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NotScored', 'Application not scored'), ('Scored', 'Application scored')], default='NotScored', max_length=100)),
                ('application_score', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_applications', to='accounts.School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_application', to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Offer pending'), ('Accepted', 'Offer accepted'), ('Rejected', 'Offer rejected'), ('Expired', 'Offer expired')], default='Pending', max_length=100)),
                ('start_at', models.DateField(auto_now=True)),
                ('expire_at', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_offers', to='accounts.School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_offer', to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('is_rated', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_review', to='review.Application')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_review', to='accounts.Staff')),
            ],
        ),
    ]
