# Generated by Django 2.1.1 on 2018-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='educational_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_text',
            field=models.CharField(max_length=1000),
        ),
    ]
