# Generated by Django 2.1.1 on 2018-09-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_school_application_reviews_required'),
        ('review', '0003_auto_20180909_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_applications', to='accounts.Batch'),
        ),
    ]
