# Generated by Django 2.0.8 on 2019-03-03 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='participations',
        ),
        migrations.AddField(
            model_name='school',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='school.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participation',
            name='participation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='participation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='school.School'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
