# Generated by Django 2.0.8 on 2019-01-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('school', '0002_auto_20190126_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user_id',
        ),
        migrations.AddField(
            model_name='school',
            name='owner',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
