# Generated by Django 2.0.10 on 2019-01-27 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('school', '0002_school_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user_id',
        ),
        migrations.AddField(
            model_name='school',
            name='owner',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
            preserve_default=False,
        ),
    ]
