# Generated by Django 2.0.10 on 2019-02-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_auto_20190204_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.DateField()),
                ('participation_type', models.CharField(choices=[('o', 'Owner'), ('s', 'Staff')], max_length=1, verbose_name='Participation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='score',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='score',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='school',
        ),
        migrations.AlterField(
            model_name='score',
            name='staff',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AddField(
            model_name='school',
            name='participations',
            field=models.ManyToManyField(through='school.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
