# Generated by Django 2.0.8 on 2019-01-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0003_auto_20190127_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='owner',
        ),
        migrations.AddField(
            model_name='school',
            name='user_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
