# Generated by Django 2.0.10 on 2019-01-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190129_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('u', 'Unknown'), ('m', 'Male'), ('f', 'Female')], default='u', max_length=1, verbose_name='Gender')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('educational_info', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('application_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='application_score', to='school.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='school_staff', to='school.School'),
        ),
        migrations.AddField(
            model_name='season',
            name='school',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='school_season', to='school.School'),
        ),
        migrations.AddField(
            model_name='score',
            name='staff',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='staff_score', to='school.Staff'),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='school_application', to='school.School'),
        ),
    ]
