# Generated by Django 2.0.8 on 2019-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190127_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
